//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagueEF.Core.Web.ExtNET {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZagueEF.Core.Web.ExtNET.Literales", typeof(Literales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar....
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es requerido..
        /// </summary>
        internal static string CampoRequerido {
            get {
                return ResourceManager.GetString("CampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo tiene que estar en formato de email válido (xyz@xyz.com)..
        /// </summary>
        internal static string FormatoDeEmailIncorrecto {
            get {
                return ResourceManager.GetString("FormatoDeEmailIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud mínima requerida no se cumple [{0} caracteres]..
        /// </summary>
        internal static string LongitudMinimaRequerida {
            get {
                return ResourceManager.GetString("LongitudMinimaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Seleccione --.
        /// </summary>
        internal static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor máximo permitido es: {0}.
        /// </summary>
        internal static string ValorMaximoPermitido {
            get {
                return ResourceManager.GetString("ValorMaximoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor mínimo permitido es: {0}.
        /// </summary>
        internal static string ValorMinimoPermitido {
            get {
                return ResourceManager.GetString("ValorMinimoPermitido", resourceCulture);
            }
        }
    }
}
