//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeIglesiasV2.Website.Paginas {
    
    
    public partial class CatalogoDeMiembros {
        
        /// <summary>
        /// Filtros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.FiltrosMiembros Filtros;
        
        /// <summary>
        /// pnlEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanelCatalogo pnlEdicion;
        
        /// <summary>
        /// colsEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ColumnLayout colsEdicion;
        
        /// <summary>
        /// colEdicion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colEdicion1;
        
        /// <summary>
        /// ZCompositeField1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField1;
        
        /// <summary>
        /// registroId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroId;
        
        /// <summary>
        /// registroBotonFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button registroBotonFoto;
        
        /// <summary>
        /// ZCompositeField2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField2;
        
        /// <summary>
        /// registroEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroEmail;
        
        /// <summary>
        /// registroNoTieneEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCheckbox registroNoTieneEmail;
        
        /// <summary>
        /// ZCompositeField4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField4;
        
        /// <summary>
        /// registroPrimerNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroPrimerNombre;
        
        /// <summary>
        /// registroSegundoNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroSegundoNombre;
        
        /// <summary>
        /// ZCompositeField5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField5;
        
        /// <summary>
        /// registroApellidoPaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroApellidoPaterno;
        
        /// <summary>
        /// registroApellidoMaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroApellidoMaterno;
        
        /// <summary>
        /// registroCelula control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroCelula;
        
        /// <summary>
        /// registroGenero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroGenero;
        
        /// <summary>
        /// registroAsisteIglesia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCheckbox registroAsisteIglesia;
        
        /// <summary>
        /// registroPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroPassword;
        
        /// <summary>
        /// colEdicion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colEdicion2;
        
        /// <summary>
        /// registroMunicipio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBoxMunicipio registroMunicipio;
        
        /// <summary>
        /// ZCompositeField3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField3;
        
        /// <summary>
        /// registroColonia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroColonia;
        
        /// <summary>
        /// registroDireccion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroDireccion;
        
        /// <summary>
        /// registroFechaDeNacimiento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField registroFechaDeNacimiento;
        
        /// <summary>
        /// registroEstadoCivil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroEstadoCivil;
        
        /// <summary>
        /// registroTelCasa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelCasa;
        
        /// <summary>
        /// registroTelMovil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelMovil;
        
        /// <summary>
        /// registroTelTrabajo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelTrabajo;
        
        /// <summary>
        /// registroConyuge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple registroConyuge;
        
        /// <summary>
        /// wndFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Window wndFoto;
        
        /// <summary>
        /// pnlFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.FormPanel pnlFoto;
        
        /// <summary>
        /// registroFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Image registroFoto;
        
        /// <summary>
        /// registroUploadFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.FileUploadField registroUploadFoto;
        
        /// <summary>
        /// Resultados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.ResultadoMiembros Resultados;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos Master {
            get {
                return ((AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos)(base.Master));
            }
        }
    }
}
