//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeIglesiasV2.Website.Paginas.Alabanza {
    
    
    public partial class Calendario {
        
        /// <summary>
        /// StoreEnsayos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreEnsayos;
        
        /// <summary>
        /// StoreEventos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreEventos;
        
        /// <summary>
        /// StoreDiasNoDisponibles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreDiasNoDisponibles;
        
        /// <summary>
        /// wndAgregarDiasNoDisponibles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZModalWindow wndAgregarDiasNoDisponibles;
        
        /// <summary>
        /// pnlAgregarDiasNoDisponibles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZFormPanel pnlAgregarDiasNoDisponibles;
        
        /// <summary>
        /// registroDiasNoDisponiblesRazon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroDiasNoDisponiblesRazon;
        
        /// <summary>
        /// registroDiasNoDisponiblesFechaInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField registroDiasNoDisponiblesFechaInicio;
        
        /// <summary>
        /// registroDiasNoDisponiblesFechaFin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField registroDiasNoDisponiblesFechaFin;
        
        /// <summary>
        /// btnAgregarDiaNoDisponible control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnAgregarDiaNoDisponible;
        
        /// <summary>
        /// Viewport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Viewport Viewport;
        
        /// <summary>
        /// pnlDatosGenerales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanel pnlDatosGenerales;
        
        /// <summary>
        /// gridEnsayos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZGridPanel gridEnsayos;
        
        /// <summary>
        /// gridEventos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZGridPanel gridEventos;
        
        /// <summary>
        /// gridDiasNoDisponibles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZGridPanel gridDiasNoDisponibles;
        
        /// <summary>
        /// btnAgregarNuevoDiaNoDisponible control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnAgregarNuevoDiaNoDisponible;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AdministradorDeIglesiasV2.Website.MainMasterPage Master {
            get {
                return ((AdministradorDeIglesiasV2.Website.MainMasterPage)(base.Master));
            }
        }
    }
}
