//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Literales", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asistencia en esta fecha fue previamente cancelada; aun así se puede guardar asistencia y se borrará la cancelación de la asistencia. Razón de la cancelacion: {0}.
        /// </summary>
        internal static string AsistenciaACelulaPreviamenteCancelada {
            get {
                return ResourceManager.GetString("AsistenciaACelulaPreviamenteCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia reiniciada correctamente..
        /// </summary>
        internal static string AsistenciaDeCelulaReiniciada {
            get {
                return ResourceManager.GetString("AsistenciaDeCelulaReiniciada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia guardada correctamente..
        /// </summary>
        internal static string AsistenciaGuardadaCorrectamente {
            get {
                return ResourceManager.GetString("AsistenciaGuardadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el ciclo de un registro existente; es necesario eliminar el anterior y crear un nuevo..
        /// </summary>
        internal static string CambioDeCicloNoPermitido {
            get {
                return ResourceManager.GetString("CambioDeCicloNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambios aplicados correctamente..
        /// </summary>
        internal static string CambiosAplicados {
            get {
                return ResourceManager.GetString("CambiosAplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno de los campos tiene un valor no válido; favor de volverlo a intentar..
        /// </summary>
        internal static string CampoNoValido {
            get {
                return ResourceManager.GetString("CampoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cancelación de la asistencia de la célula se ha guardado correctamente..
        /// </summary>
        internal static string CancelacionDeAsistenciaGuardadaCorrectamente {
            get {
                return ResourceManager.GetString("CancelacionDeAsistenciaGuardadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar una célula antes de continuar..
        /// </summary>
        internal static string CelulaNecesaria {
            get {
                return ResourceManager.GetString("CelulaNecesaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar una célula y fecha antes de continuar..
        /// </summary>
        internal static string CelulaYFechaNecesarias {
            get {
                return ResourceManager.GetString("CelulaYFechaNecesarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los pasos no tiene definido un ciclo correcto..
        /// </summary>
        internal static string CicloNoCorrecto {
            get {
                return ResourceManager.GetString("CicloNoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ha sido actualizada correctamente..
        /// </summary>
        internal static string ContrasenaCambiadaCorrectamente {
            get {
                return ResourceManager.GetString("ContrasenaCambiadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cargar el registro seleccionado, es posible que ya se encuentre eliminado..
        /// </summary>
        internal static string ErrorAlCargar {
            get {
                return ResourceManager.GetString("ErrorAlCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los filtros contienen valores/datos inválidos. Favor de volver a intentar..
        /// </summary>
        internal static string FiltrosConDatosInvalidos {
            get {
                return ResourceManager.GetString("FiltrosConDatosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar una grupo y fecha antes de continuar..
        /// </summary>
        internal static string GrupoYFechaNecesarias {
            get {
                return ResourceManager.GetString("GrupoYFechaNecesarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los filtros actuales regresaron {0} resultados; por seguridad solo se mostrarán los primeros {1}..
        /// </summary>
        internal static string LimiteDeResultadosExcedido {
            get {
                return ResourceManager.GetString("LimiteDeResultadosExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operacion de borrar no es posible de efectuarse en este caso, el registro es solo modificable..
        /// </summary>
        internal static string OperacionNovalidaBorrar {
            get {
                return ResourceManager.GetString("OperacionNovalidaBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no se encuentra en la base de datos; es posible que alguien mas ya lo haya eliminado..
        /// </summary>
        internal static string RegistroInexistente {
            get {
                return ResourceManager.GetString("RegistroInexistente", resourceCulture);
            }
        }
    }
}
