//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeIglesiasV2.Website.Paginas {
    
    
    public partial class CatalogoDeCapitanes {
        
        /// <summary>
        /// Filtros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.FiltrosMiembros Filtros;
        
        /// <summary>
        /// pnlEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanelCatalogo pnlEdicion;
        
        /// <summary>
        /// colsEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ColumnLayout colsEdicion;
        
        /// <summary>
        /// colEdicion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colEdicion1;
        
        /// <summary>
        /// Container2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container2;
        
        /// <summary>
        /// BuscadorCapitan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.Buscador BuscadorCapitan;
        
        /// <summary>
        /// Container1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container1;
        
        /// <summary>
        /// BuscadorIntegrantes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.Buscador BuscadorIntegrantes;
        
        /// <summary>
        /// Resultados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.ResultadoMiembros Resultados;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos Master {
            get {
                return ((AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos)(base.Master));
            }
        }
    }
}
