//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeIglesiasV2.Website.Paginas {
    
    
    public partial class CatalogoDeBoletas {
        
        /// <summary>
        /// StoreResultados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreResultados;
        
        /// <summary>
        /// StoreReportes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreReportes;
        
        /// <summary>
        /// StoreGeneros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreGeneros;
        
        /// <summary>
        /// StoreEstadosCiviles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreEstadosCiviles;
        
        /// <summary>
        /// StoreCultos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreCultos;
        
        /// <summary>
        /// StoreRazonesDeVisita control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreRazonesDeVisita;
        
        /// <summary>
        /// StoreEstatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreEstatus;
        
        /// <summary>
        /// StoreCategorias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Store StoreCategorias;
        
        /// <summary>
        /// wndAgregarReporte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZModalWindow wndAgregarReporte;
        
        /// <summary>
        /// pnlAgregarReporte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanel pnlAgregarReporte;
        
        /// <summary>
        /// registroReporteNuevo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextArea registroReporteNuevo;
        
        /// <summary>
        /// btnAgregarReporte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnAgregarReporte;
        
        /// <summary>
        /// wndCrearMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZModalWindow wndCrearMiembro;
        
        /// <summary>
        /// pnlCrearMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanel pnlCrearMiembro;
        
        /// <summary>
        /// registroBoletaId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Hidden registroBoletaId;
        
        /// <summary>
        /// registroCelulaDeMiembroCreado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple registroCelulaDeMiembroCreado;
        
        /// <summary>
        /// btnCrearMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnCrearMiembro;
        
        /// <summary>
        /// btnNoCrearMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnNoCrearMiembro;
        
        /// <summary>
        /// pnlFiltros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanelCatalogo pnlFiltros;
        
        /// <summary>
        /// colsFiltros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ColumnLayout colsFiltros;
        
        /// <summary>
        /// colFiltros1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colFiltros1;
        
        /// <summary>
        /// filtroId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField filtroId;
        
        /// <summary>
        /// filtroEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroEmail;
        
        /// <summary>
        /// ZCompositeField6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField6;
        
        /// <summary>
        /// filtroPrimerNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroPrimerNombre;
        
        /// <summary>
        /// filtroSegundoNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroSegundoNombre;
        
        /// <summary>
        /// ZCompositeField7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField7;
        
        /// <summary>
        /// filtroApellidoPaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroApellidoPaterno;
        
        /// <summary>
        /// filtroApellidoMaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroApellidoMaterno;
        
        /// <summary>
        /// filtroGenero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroGenero;
        
        /// <summary>
        /// Container5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container5;
        
        /// <summary>
        /// filtroInvitadoPorMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple filtroInvitadoPorMiembro;
        
        /// <summary>
        /// filtroCulto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroCulto;
        
        /// <summary>
        /// filtroFechaDeCulto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField filtroFechaDeCulto;
        
        /// <summary>
        /// filtroRazonDeVisita control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroRazonDeVisita;
        
        /// <summary>
        /// filtroEstatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroEstatus;
        
        /// <summary>
        /// filtroCategoria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroCategoria;
        
        /// <summary>
        /// colFiltros2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colFiltros2;
        
        /// <summary>
        /// filtroMunicipio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBoxMunicipio filtroMunicipio;
        
        /// <summary>
        /// ZCompositeField8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField8;
        
        /// <summary>
        /// filtroColonia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroColonia;
        
        /// <summary>
        /// filtroDireccion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroDireccion;
        
        /// <summary>
        /// filtroEdad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField filtroEdad;
        
        /// <summary>
        /// filtroEstadoCivil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZMultiCombo filtroEstadoCivil;
        
        /// <summary>
        /// Container3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container3;
        
        /// <summary>
        /// filtroCelulaAsignada control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple filtroCelulaAsignada;
        
        /// <summary>
        /// Container4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container4;
        
        /// <summary>
        /// filtroMiembroAsignada control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple filtroMiembroAsignada;
        
        /// <summary>
        /// filtroTel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField filtroTel;
        
        /// <summary>
        /// filtroObservaciones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField filtroObservaciones;
        
        /// <summary>
        /// pnlEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZPanelCatalogo pnlEdicion;
        
        /// <summary>
        /// colsEdicion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ColumnLayout colsEdicion;
        
        /// <summary>
        /// colEdicion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colEdicion1;
        
        /// <summary>
        /// registroId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroId;
        
        /// <summary>
        /// ZCompositeField2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField2;
        
        /// <summary>
        /// registroEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroEmail;
        
        /// <summary>
        /// registroNoTieneEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCheckbox registroNoTieneEmail;
        
        /// <summary>
        /// ZCompositeField4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField4;
        
        /// <summary>
        /// registroPrimerNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroPrimerNombre;
        
        /// <summary>
        /// registroSegundoNombre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroSegundoNombre;
        
        /// <summary>
        /// ZCompositeField5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField5;
        
        /// <summary>
        /// registroApellidoPaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroApellidoPaterno;
        
        /// <summary>
        /// registroApellidoMaterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroApellidoMaterno;
        
        /// <summary>
        /// registroGenero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroGenero;
        
        /// <summary>
        /// Container6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container6;
        
        /// <summary>
        /// registroInvitadoPorMiembro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple registroInvitadoPorMiembro;
        
        /// <summary>
        /// registroCulto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroCulto;
        
        /// <summary>
        /// registroFechaDeCulto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField registroFechaDeCulto;
        
        /// <summary>
        /// registroRazonDeVisita control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroRazonDeVisita;
        
        /// <summary>
        /// registroEstatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroEstatus;
        
        /// <summary>
        /// registroCategoria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroCategoria;
        
        /// <summary>
        /// colEdicion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container colEdicion2;
        
        /// <summary>
        /// registroMunicipio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBoxMunicipio registroMunicipio;
        
        /// <summary>
        /// ZCompositeField3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZCompositeField ZCompositeField3;
        
        /// <summary>
        /// registroColonia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroColonia;
        
        /// <summary>
        /// registroDireccion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroDireccion;
        
        /// <summary>
        /// registroFechaDeNacimiento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZDateField registroFechaDeNacimiento;
        
        /// <summary>
        /// registroEdad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroEdad;
        
        /// <summary>
        /// registroEstadoCivil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZComboBox registroEstadoCivil;
        
        /// <summary>
        /// Container2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container2;
        
        /// <summary>
        /// registroCelulaAsignada control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple registroCelulaAsignada;
        
        /// <summary>
        /// Container1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Container Container1;
        
        /// <summary>
        /// registroMiembroAsignada control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdministradorDeIglesiasV2.Website.Paginas.UserControls.BuscadorSimple registroMiembroAsignada;
        
        /// <summary>
        /// registroTelCasa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelCasa;
        
        /// <summary>
        /// registroTelMovil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelMovil;
        
        /// <summary>
        /// registroTelTrabajo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZNumberField registroTelTrabajo;
        
        /// <summary>
        /// registroObservaciones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZTextField registroObservaciones;
        
        /// <summary>
        /// btnCargarDatosDeBoletaAnterior control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnCargarDatosDeBoletaAnterior;
        
        /// <summary>
        /// GridDeReportes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZGridCatalogo GridDeReportes;
        
        /// <summary>
        /// btnAgregarNuevoReporte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button btnAgregarNuevoReporte;
        
        /// <summary>
        /// GridDeResultados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZagueEF.Core.Web.ExtNET.Controls.ZGridCatalogo GridDeResultados;
        
        /// <summary>
        /// registroNumeroDeBoletas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.DisplayField registroNumeroDeBoletas;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos Master {
            get {
                return ((AdministradorDeIglesiasV2.Website.Paginas.MasterPages.Catalogos)(base.Master));
            }
        }
    }
}
